# Generated by Django 5.1.7 on 2025-03-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=100)),
                ('average_before_normalization', models.FloatField()),
                ('average_after_normalization', models.FloatField()),
                ('data_size', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
