# Generated by Django 5.1.7 on 2025-03-14 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='device_id',
        ),
        migrations.AddField(
            model_name='image',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='images.device'),
            preserve_default=False,
        ),
    ]
