# Generated by Django 5.1.7 on 2025-03-14 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_device_device_name_alter_device_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='created_updated',
            new_name='updated_date',
        ),
    ]
